### ISSUE TITLE
Limited view not fully working

### ISSUE THREAD

**Issue by M-J-Robbins** [RebelMail/slif-extension#14]
The limited view doesn't seem to be working properly.
It should be removing any media query with (-webkit-device-pixel-ratio)

e.g. 
@media screen and (-webkit-device-pixel-ratio)
@media only screen and (max-device-width :846px)and (-webkit-device-pixel-ratio)
@media screen and (device-width:320px)and (device-height:480px)and (-webkit-device-pixel-ratio:2)

Also removing ```<style external>``` would be good

Cheers :)

**Comment by motdotla** [comment]
Fix is here: https://github.com/RebelMail/slif-extension/pull/15

What do you mean - `Also removing would be good</p> <p>Cheers :)</p>` ?

**Comment by motdotla** [comment]
Latest `0.1.2` is here: https://chrome.google.com/webstore/detail/jhjflphjohlmpjdcohhpadnjhgamlfdo/publish-delayed?authuser=1

**Comment by M-J-Robbins** [comment]
@motdotla Ah sorry didn't put that in a code block so messed up, was meant to say ```<style external>```
All seems to be working well now.
Cheers

**Comment by motdotla** [comment]
@M-J-Robbins  For removing `<style external>` should that happen on

+ limited

or on

+ limited
+ fallback
+ static

**Comment by motdotla** [comment]
I've got external tag removal going here: https://github.com/RebelMail/slif-extension/pull/16

Currently just set to limited.

**Comment by M-J-Robbins** [comment]
@motdotla Yeah limited static and fallback.  Should only show for interactive. 
Cheers mate.

**Comment by motdotla** [comment]
https://github.com/RebelMail/slif-extension/pull/16

https://chrome.google.com/webstore/detail/jhjflphjohlmpjdcohhpadnjhgamlfdo/publish-delayed?authuser=1
